"""Add last_completed_task column to UserProfile

Revision ID: 80b33dace782
Revises: 
Create Date: 2025-03-17 00:24:49.668740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '80b33dace782'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_completed_task', sa.DateTime(), nullable=True))
        batch_op.drop_column('tasks_completed')
        batch_op.drop_column('next_level_xp')
        batch_op.drop_column('achievements')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievements', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('next_level_xp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tasks_completed', sa.INTEGER(), nullable=True))
        batch_op.drop_column('last_completed_task')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_user_id'))

    # ### end Alembic commands ###
